/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButon: typeof import('element-plus/es')['ElButon']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpService: typeof import('~icons/ep/service')['default']
  }
}
